filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "log"
setup.template.pattern: "*"

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
      - /var/log/*/*.log

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  timeout: 10
  path: "/api/default/"
  index: default
  hosts: ['${ELASTICSEARCH_HOSTS:openobserve:5080}']
  username: '${ELASTICSEARCH_USERNAME:root@example.com}'
  password: '${ELASTICSEARCH_PASSWORD:Complexpass#123}'

# 只能有一个output 
# output.kafka:
#   hosts: ["redpanda-0:9092"]
#   topic: 'log-topic'
#   partition.round_robin:
#     reachable_only: false

#   required_acks: 1
#   compression: gzip
#   max_message_bytes: 1000000